### ISSUE TITLE
How to contribute changes to jupyter notebooks?

### ISSUE THREAD

**Issue by KPLauritzen** [pjarnhus/DataScienceGym#5]
Is there a clear process?
What should I do about the metadata that is automatically generated when I run cells?
I can manually strip output, but that is not the only meta data added by jupyter automatically. See eg #4. 

Maybe we should have a guide for setting up a git pre-commit hook?

**Comment by pjarnhus** [comment]
Good idea!

I will look into it. I am guessing we need to clean:
* output
* metadata

Anything else?

**Comment by KPLauritzen** [comment]
See commit 33985fc667e270266431dcca841c9e876c886a08 for an example of what is added from me.

**Comment by pjarnhus** [comment]
Added a clean-up script in https://github.com/pjarnhus/Python-Step-By-Step/commit/046bc4eff04d0b4bad4806756f69a5eed422699f

Hopefully this will solve the issue. Could I ask you to test it and see, if it solves the issue?

**Comment by KPLauritzen** [comment]
Good news and bad news:

- Good: The script cleans the metadata as it should
- Bad: It completely destroys diffs by putting the .ipynb json file on one line. 

I think I might know how to fix it...

**Comment by pjarnhus** [comment]
Awesome!

Let me know, what you find

**Comment by pjarnhus** [comment]
Ah! Those tricksy little parameters you can set :) Didn't know about that one
